name: batch-inference-pipeline

on:
  workflow_run:
    workflows: [daily-feature-pipeline]
    types:
      - completed

jobs:
  test_schedule:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          chmod +x run-batch-inference-pipeline.sh
          ./run-batch-inference-pipeline.sh
