name: daily-feature-pipeline

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          
      - name: Execute Python workflows from batch script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          chmod +x run-daily-feature-pipeline.sh
          ./run-daily-feature-pipeline.sh
